DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email               VARCHAR(50),
    name                VARCHAR(50),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation          VARCHAR(2000),
    category_id         BIGINT,
    created_on          TIMESTAMP WITH TIME ZONE,
    description         VARCHAR (7000),
    event_date          TIMESTAMP WITH TIME ZONE,
    user_id             BIGINT,
    lat                 FLOAT,
    lon                 FLOAT,
    paid                BOOLEAN,
    participant_limit   INTEGER,
    published_on        TIMESTAMP WITH TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(20),
    title               VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                VARCHAR(50),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned              BOOLEAN,
    title               VARCHAR(550),
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    event_id            BIGINT,
    compilation_id      BIGINT
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created             TIMESTAMP WITH TIME ZONE,
    event_id            BIGINT,
    user_id             BIGINT,
    status              VARCHAR(20),
    CONSTRAINT uq_request_user_and_event UNIQUE (event_id, user_id)
);

ALTER TABLE IF EXISTS events ADD CONSTRAINT fk_event_to_category
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS events ADD CONSTRAINT fk_event_to_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS requests ADD CONSTRAINT fk_request_to_event
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS requests ADD CONSTRAINT fk_request_to_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS compilations_events ADD CONSTRAINT fk_to_compilations
    FOREIGN KEY (compilation_id) REFERENCES compilations(id);
ALTER TABLE IF EXISTS compilations_events ADD CONSTRAINT fk_to_events
    FOREIGN KEY (event_id) REFERENCES events(id);
